services:
  - type: web
    name: paint-house
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /
